# Resolve react_native_pods.rb with node to allow for hoisting
$RNFirebaseAsStaticFramework = true
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']

target 'snapSave' do
  config = use_native_modules!

  # Required for Firebase static frameworks
  
  
  use_frameworks! :linkage => :static

  use_react_native!(
    path: config[:reactNativePath],
    app_path: "#{Pod::Config.instance.installation_root}/.."
    )

  # gRPC pods
  pod 'gRPC-C++', :modular_headers => true
  pod 'gRPC-Core', :modular_headers => true

  # Firebase pods
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
end

post_install do |installer|
  react_native_post_install(installer)

  # Ensure gRPC pods define modules
  installer.pods_project.targets.each do |target|
    if target.name =~ /gRPC/
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE'] = 'YES'
      end
    end
  end
end

# Resolve react_native_pods.rb with node to allow for hoisting
# Resolve react_native_pods.rb with node to allow for hoisting
# $RNFirebaseAsStaticFramework = true
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!

# # Enable New Architecture
# ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# target 'snapSave' do
#   config = use_native_modules!

#   use_react_native!(
#     path: config[:reactNativePath],
#     app_path: "#{Pod::Config.instance.installation_root}/..",
#     # Enable both Fabric and Hermes for New Architecture
#     fabric_enabled: true,
#     hermes_enabled: true
#   )
  
#   use_frameworks! :linkage => :static

#   # gRPC pods with modular headers
#   pod 'gRPC-C++', :modular_headers => true
#   pod 'gRPC-Core', :modular_headers => true

#   # Firebase pods with modular headers
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'FirebaseCoreInternal', :modular_headers => true
#   pod 'FirebaseCoreExtension', :modular_headers => true
#   pod 'FirebaseFirestore', :modular_headers => true
#   pod 'FirebaseFirestoreInternal', :modular_headers => true
#   pod 'GoogleUtilities', :modular_headers => true
  
#   # Store react_native_path for use in post_install
#   target.build_configurations.each do |config|
#     config.build_settings['REACT_NATIVE_PATH'] = File.dirname(`node --print "require.resolve('react-native/package.json')"`)
#   end
# end

# post_install do |installer|
#   # Get the React Native path from the stored build setting
#   react_native_path = installer.pods_project.targets
#     .find { |target| target.name == 'snapSave' }
#     &.build_configurations
#     &.first
#     &.build_settings['REACT_NATIVE_PATH']
  
#   react_native_path ||= '../node_modules/react-native'
  
#   react_native_post_install(
#     installer,
#     react_native_path,
#     :mac_catalyst_enabled => false
#   )

#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       # Enable modular headers for gRPC
#       if target.name =~ /gRPC/
#         config.build_settings['DEFINES_MODULE'] = 'YES'
#       end
      
#       # Fix for New Architecture + Static Frameworks
#       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
#       # Disable bitcode (not needed for modern iOS)
#       config.build_settings['ENABLE_BITCODE'] = 'NO'
      
#       # Use modern build system settings
#       config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
#       config.build_settings['DEFINES_MODULE'] = 'YES'
      
#       # Fix duplicate header issue
#       config.build_settings['USE_HEADERMAP'] = 'YES'
#       config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
      
#       # Ensure C++17 for New Architecture
#       config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      
#       # Deployment target
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#     end
#   end
  
#   # Remove duplicate references
#   installer.pods_project.targets.each do |target|
#     if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
#       target.build_configurations.each do |config|
#         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#       end
#     end
#   end
# end